---
- hosts: all
  become: yes
  vars:
    packagename: apache2
    php_packages:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
      - php-cli
  tasks:
  - name: install apache2 
    apt:
      name: "{{packagename}}"
      state: present
      update_cache: yes
  - name: stating the apach2 servcie
    service:
      name: "{{packagename}}"
      state: started
      enabled: yes
  - name: debugging msg 
    debug:
      msg: installed the apach2 and started the service

  - name: installin the php packages
    apt:
      name: "{{ php_packages }}"
      state: present 
  - name: debugging msg 
    debug:
      msg: installed the all php packages names are {{php_packages}}    
  - name: example copying file with owner and permissions
    copy:
      src: "{{ item.src }}"
      dest: "{{item.dest }}"
    with_items:
      - { src: dir.conf , dest: /etc/apache2/mods-enabled/dir.conf }
      - { src: info.php , dest: /var/www/html/info.php }
  - name: debugging msg 
    debug:
      msg: copied all the files to thier locations               
  - name: restart apach service
    service:
      name: "{{packagename}}"
      state: restarted


